import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { Listing } from "@prisma/client";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { api } from "~/utils/api";

export default function ListingView() {
  const router = useRouter();
  const listing = api.listings.get.useQuery(
    {
      listingId: router.query.id as string,
    },
    {
      enabled: !!router.query.id,
    }
  );
  const listingItem = listing.data;

  if (!listingItem) {
    return;
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-6 flex min-h-screen flex-col items-center justify-center pt-16 md:pt-0 lg:mx-12">
        <div className="flex flex-col gap-4">
          <h1 className="my-6 text-2xl">{listingItem.name}</h1>
          <p>{listingItem.description}</p>
          <p className="self-end text-lg">£{listingItem.price}</p>
        </div>
      </main>
    </>
  );
}
