import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { Listing } from "@prisma/client";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";

export default function Messages() {
  const messages = api.listings.getMessage.useQuery();
  // console.log(messages.data?.length);

  return (
    <>
      <Head>
        <title>Messages</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-6 flex min-h-screen flex-col items-center pt-16 lg:mx-12">
        <div className="container mx-auto">
          <h1 className="my-6 text-2xl">Messages</h1>
          <div className="container gap-4">
            <div className="relative overflow-x-auto">
              <table className="w-full text-left text-sm text-gray-500 dark:text-gray-400">
                <thead className="bg-gray-50 text-xs uppercase text-gray-700 dark:bg-gray-700 dark:text-gray-400">
                  <tr>
                    <th scope="col" className="px-6 py-3">
                      From
                    </th>
                    <th scope="col" className="px-6 py-3">
                      Message
                    </th>
                  </tr>
                </thead>
                {messages?.data?.length ? (
                  <tbody>
                    {messages?.data?.map((message) => (
                      <tr
                        key={message.id}
                        className="border-b bg-white dark:border-gray-700 dark:bg-gray-800"
                      >
                        <td className="px-6 py-4">{message.fromUserName}</td>
                        <td className="px-6 py-4">{message.message}</td>
                      </tr>
                    ))}
                  </tbody>
                ) : (
                  <tbody>
                    <tr className="border-b bg-white dark:border-gray-700 dark:bg-gray-800">
                      <td className="px-6 py-4">No new messages</td>
                    </tr>
                  </tbody>
                )}
              </table>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
